services:
  service-api-nomos:
    container_name: container-api-nomos
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=db-api-nomos
    volumes:
      - pgdata:/bitnami/postgresql  # Volume persistente para os dados do PostgreSQL
    networks:
      - api-nomos-network           # Usar rede existente

# Definir volumes
volumes:
  pgdata:
    driver: local  # Usar driver local para volumes persistentes

# Definir redes
networks:
  api-nomos-network:
    external: true  # Indica que esta rede jรก existe
