version: "3.9"

services:
  service-api-nomos:
    container_name: container-api-nomos
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=db-api-nomos
